// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1627300440);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1627299840);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1627300080);
user_pref("app.update.lastUpdateTime.region-update-timer", 1616578835);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1627300200);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1627299960);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1627300320);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1627300680);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1627300560);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1616577964);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.migration.version", 104);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5fc4b86e-f0a1-4291-9e74-b96720ee312e}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1627299824097");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1627301638097");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210310152336");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1627299811");
user_pref("browser.slowStartup.averageTime", 1393);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20210310152336");
user_pref("browser.startup.homepage_override.mstone", "86.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1627299811);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.tipShownCount.searchTip_onboard", 4);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1616577970733");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "86.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.cache.lastUpdate", 1627300442);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210310152336");
user_pref("extensions.lastAppVersion", "86.0.1");
user_pref("extensions.lastPlatformVersion", "86.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"b873358d-26eb-42bf-b685-2cafab1611cd\",\"formautofill@mozilla.org\":\"9df67252-8e8c-47b1-a26f-0880c2ec7c7c\",\"screenshots@mozilla.org\":\"10264976-189b-4c15-a532-e0167b1f4208\",\"webcompat-reporter@mozilla.org\":\"c98426bf-cc8f-499b-be71-aee638984c5d\",\"webcompat@mozilla.org\":\"e718b90a-ae75-4099-98c0-c406f7747263\",\"default-theme@mozilla.org\":\"fdc9e542-03be-4d3a-9ed1-38990a504579\",\"google@search.mozilla.org\":\"c0113e01-841c-4cfa-9f93-09afca734c29\",\"amazondotcom@search.mozilla.org\":\"8e749491-73a8-42c7-8d2b-eac27df14116\",\"wikipedia@search.mozilla.org\":\"446198e6-5610-46f0-a24f-eba18d52b54a\",\"bing@search.mozilla.org\":\"d6e82003-b384-4d55-9e96-fa3064ac925a\",\"ddg@search.mozilla.org\":\"f20c13ea-fc0c-4656-b57c-d5b9d4a684e1\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1616577970);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1627300111);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1616578064);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20210310152336");
user_pref("media.gmp-manager.lastCheck", 1627299873);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.trr.blocklist_cleanup_done", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1627300113);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.purge_trackers.last_purge", "1627300112031");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.pki.mitm_canary_issuer", "CN=\"Zscaler Intermediate Root CA (zscaler.net) (t) \",OU=Zscaler Inc.,O=Zscaler Inc.,ST=California,C=US");
user_pref("security.sandbox.content.tempDirSuffix", "432e3bcf-d439-41fa-a9e7-6406e7ff9673");
user_pref("security.sandbox.plugin.tempDirSuffix", "843d1c99-223d-4101-8ba6-8956e3814241");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1627300111);
user_pref("toolkit.startup.last_success", 1627299810);
user_pref("toolkit.telemetry.cachedClientID", "6a142e66-33d3-4b92-9d0a-57c82e319b20");
user_pref("toolkit.telemetry.previousBuildID", "20210310152336");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
